import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  CheckCircle2,
  ChevronDown,
  GraduationCap,
  LayoutDashboard,
  MoreHorizontal,
  Plus,
  Search,
  SlidersHorizontal,
  Users,
  X,
} from "lucide-react";

const teachers = [
  { initials: "MM", name: "Tr. Mary Wanjiku", role: "Class teacher · Grade 7 East", subjects: ["Mathematics", "Integrated Science"], classes: ["Grade 7 East", "Grade 9 North"], learners: 78, status: "Active", tone: "lavender" },
  { initials: "DO", name: "Tr. David Otieno", role: "Class teacher · Grade 8 West", subjects: ["English", "Social Studies"], classes: ["Grade 8 West", "Grade 10 East"], learners: 64, status: "Active", tone: "mint" },
  { initials: "SN", name: "Tr. Sarah Njeri", role: "Subject teacher", subjects: ["Kiswahili", "Creative Arts"], classes: ["Grade 6 North", "Grade 7 East", "Grade 8 West"], learners: 112, status: "Active", tone: "peach" },
  { initials: "JK", name: "Tr. James Kamau", role: "Class teacher · Grade 9 North", subjects: ["Integrated Science", "Agriculture"], classes: ["Grade 9 North", "Grade 11 Central"], learners: 58, status: "On leave", tone: "blue" },
  { initials: "LW", name: "Tr. Lucy Wambui", role: "Subject teacher", subjects: ["Mathematics", "Computer Studies"], classes: ["Grade 7 East", "Grade 9 North", "Grade 12 Central"], learners: 96, status: "Active", tone: "lavender" },
];

export default function Teachers() {
  const [query, setQuery] = useState("");
  const [subject, setSubject] = useState("All subjects");
  const [showAdd, setShowAdd] = useState(false);
  const subjects = ["All subjects", "Mathematics", "Integrated Science", "English", "Social Studies", "Kiswahili", "Computer Studies"];
  const filtered = useMemo(() => teachers.filter((teacher) => {
    const matchesQuery = `${teacher.name} ${teacher.role} ${teacher.subjects.join(" ")} ${teacher.classes.join(" ")}`.toLowerCase().includes(query.toLowerCase());
    const matchesSubject = subject === "All subjects" || teacher.subjects.includes(subject);
    return matchesQuery && matchesSubject;
  }), [query, subject]);

  return (
    <div className="min-h-screen bg-[#f8f7fb] text-[#302a40]">
      <header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-[#ebe7f1] bg-[#f8f7fb]/90 px-5 backdrop-blur-xl lg:px-10"><div className="flex items-center gap-3"><Link href="/dashboard" className="grid h-9 w-9 place-items-center rounded-xl border border-[#e8e3ee] bg-white text-[#765abd] transition hover:border-[#cfc1e8]" aria-label="Back to dashboard"><ArrowLeft className="h-4 w-4" /></Link><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a39aa9]">People & curriculum</p><h1 className="mt-1 text-[19px] font-semibold tracking-[-.04em] text-[#383044]">Class teachers & subjects</h1></div></div><div className="flex items-center gap-2"><button onClick={() => toast.info("Teacher directory filters are active.")} className="hidden items-center gap-2 rounded-xl border border-[#e9e5ef] bg-white px-3 py-2.5 text-[11px] font-semibold text-[#6d6478] sm:flex"><SlidersHorizontal className="h-3.5 w-3.5" /> Manage filters</button><button onClick={() => setShowAdd(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#6e52b8] px-3.5 py-2.5 text-[11px] font-semibold text-white shadow-[0_7px_14px_rgba(110,82,184,.16)] transition hover:-translate-y-0.5 hover:bg-[#5d439e]"><Plus className="h-3.5 w-3.5" /> Add teacher</button></div></header>

      <main className="mx-auto max-w-[1400px] px-5 py-7 lg:px-10 lg:py-9">
        <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[11px] text-[#a29aaa]"><Link href="/dashboard" className="transition hover:text-[#6e52b8]">Overview</Link><span>/</span><span>Teachers</span></div><h2 className="mt-3 text-[29px] font-semibold tracking-[-.055em] text-[#342d42]">Know who teaches what.</h2><p className="mt-1.5 max-w-[560px] text-[13px] leading-6 text-[#948b9f]">Keep class-teacher responsibilities and subject coverage visible across every grade, stream, and learning area.</p></div><div className="flex items-center gap-3 text-[11px] text-[#91889d]"><span className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-[#62a17e]" /> 18 active teachers</span><span className="h-1 w-1 rounded-full bg-[#c8c0cc]" /><span>2024 / 25</span></div></div>

        <div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={Users} value="18" label="Total teachers" tone="lavender" /><Stat icon={GraduationCap} value="12" label="Class teachers" tone="mint" /><Stat icon={BookOpen} value="34" label="Subjects covered" tone="peach" /></div>

        <section className="mt-6 rounded-[20px] border border-[#ebe7f1] bg-white p-5 shadow-[0_5px_20px_rgba(60,45,92,.025)] sm:p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 className="text-[14px] font-semibold text-[#4a4256]">Teacher coverage</h3><p className="mt-1 text-[11px] text-[#a39aa9]">Class-teacher assignments and subject timetables in one view.</p></div><div className="flex flex-col gap-2 sm:flex-row"><div className="flex items-center rounded-xl border border-[#e9e5ef] bg-[#fcfbfd] px-3"><Search className="h-3.5 w-3.5 text-[#aaa1b2]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search teacher, class, subject" className="w-full bg-transparent py-2.5 pl-2 text-[11px] outline-none placeholder:text-[#b2aab8] sm:w-[220px]" /></div><div className="relative"><select value={subject} onChange={(event) => setSubject(event.target.value)} className="w-full appearance-none rounded-xl border border-[#e9e5ef] bg-[#fcfbfd] px-3 py-2.5 pr-8 text-[11px] font-semibold text-[#6b6276] outline-none focus:border-[#b49bdd] sm:w-[170px]"><option>All subjects</option>{subjects.slice(1).map((item) => <option key={item}>{item}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#a49bab]" /></div></div></div>

          <div className="mt-6 space-y-3">{filtered.map((teacher) => <article key={teacher.name} className="group rounded-2xl border border-[#f0edf4] p-4 transition hover:border-[#d9ccef] hover:bg-[#fdfbff] sm:p-5"><div className="grid gap-4 xl:grid-cols-[1.4fr_1fr_1fr_auto] xl:items-center"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-[14px] text-[11px] font-bold ${teacher.tone === "lavender" ? "bg-[#ded2f3] text-[#624b98]" : teacher.tone === "mint" ? "bg-[#d7eddf] text-[#4d8464]" : teacher.tone === "peach" ? "bg-[#f9dfd1] text-[#a96849]" : "bg-[#dceaf5] text-[#52738e]"}`}>{teacher.initials}</span><div className="min-w-0"><h4 className="text-[13px] font-semibold text-[#51485f]">{teacher.name}</h4><p className="mt-1 text-[10px] text-[#9c93a5]">{teacher.role}</p></div></div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#aaa1b0]">Subjects teaching</p><div className="flex flex-wrap gap-1.5">{teacher.subjects.map((item) => <span key={item} className="rounded-md bg-[#eee9fb] px-2 py-1 text-[10px] font-semibold text-[#7056ae]">{item}</span>)}</div></div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#aaa1b0]">Assigned classes</p><div className="flex flex-wrap gap-1.5">{teacher.classes.map((item) => <span key={item} className="rounded-md border border-[#eeeaf3] bg-white px-2 py-1 text-[10px] font-medium text-[#746b7d]">{item}</span>)}</div></div><div className="flex items-center justify-between gap-5 xl:justify-end"><div><p className="text-[10px] text-[#aaa1b0]">Learners</p><p className="mt-1 text-[15px] font-semibold text-[#4e455d]">{teacher.learners}</p></div><span className={`rounded-md px-2 py-1 text-[9px] font-semibold ${teacher.status === "Active" ? "bg-[#e9f5ef] text-[#5e9976]" : "bg-[#fff0e7] text-[#b77857]"}`}>{teacher.status}</span><button className="rounded-lg p-1.5 text-[#aaa1b1] transition hover:bg-[#f3eefb] hover:text-[#6e52b8]" onClick={() => toast.info(`Opening ${teacher.name}’s teaching profile.`)} aria-label={`Open ${teacher.name}`}><MoreHorizontal className="h-4 w-4" /></button></div></div></article>)}{filtered.length === 0 && <div className="rounded-2xl border border-dashed border-[#dcd3eb] bg-[#faf8fe] p-12 text-center"><p className="text-[13px] font-semibold text-[#5d536a]">No teachers match these filters.</p><p className="mt-1 text-[11px] text-[#9d94a8]">Try another name, class, or subject.</p></div>}</div></section>

        <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-[18px] border border-[#ebe7f1] bg-[#2f2940] p-5 text-white"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-xl bg-white/10 text-[#cbbaf0]"><LayoutDashboard className="h-4 w-4" /></div><span className="text-[12px] font-semibold">Class-teacher view</span></div><p className="mt-4 max-w-[390px] text-[12px] leading-6 text-[#b7afc6]">Quickly see which teacher owns the day-to-day academic picture for each stream.</p><button onClick={() => toast.info("Class-teacher matrix opened.")} className="mt-4 inline-flex items-center gap-2 text-[11px] font-semibold text-[#d0c0f2]">Open class matrix <ArrowRight className="h-3.5 w-3.5" /></button></div><div className="rounded-[18px] border border-[#ebe7f1] bg-[#f1edfb] p-5"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-xl bg-white text-[#7359b3]"><BookOpen className="h-4 w-4" /></div><span className="text-[12px] font-semibold text-[#55486d]">Subject coverage</span></div><p className="mt-4 max-w-[390px] text-[12px] leading-6 text-[#8c809b]">See where a subject is taught, who owns the markbook, and which classes still need coverage.</p><button onClick={() => toast.info("Subject coverage report opened.")} className="mt-4 inline-flex items-center gap-2 text-[11px] font-semibold text-[#7359b3]">View coverage report <ArrowRight className="h-3.5 w-3.5" /></button></div></div>
      </main>

      {showAdd && <div className="fixed inset-0 z-50 grid place-items-center bg-[#2d2540]/30 px-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-[420px] rounded-[24px] bg-white p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-[20px] font-semibold tracking-[-.04em] text-[#3a3248]">Add a teacher</h2><p className="mt-1.5 text-[12px] text-[#948b9f]">Set their class-teacher and subject responsibilities.</p></div><button className="rounded-lg p-1.5 text-[#a49bab] hover:bg-[#f7f4fa]" aria-label="Close" onClick={() => setShowAdd(false)}><X className="h-4 w-4" /></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Field label="Teacher name" placeholder="Tr. Mary Wanjiku" /><Field label="Role" placeholder="Class teacher" /><Field label="Subject 1" placeholder="Mathematics" /><Field label="Subject 2" placeholder="Integrated Science" /></div><div className="mt-5 flex justify-end gap-2"><button className="rounded-xl px-4 py-2.5 text-[12px] font-semibold text-[#7a7184] hover:bg-[#f7f4fa]" onClick={() => setShowAdd(false)}>Cancel</button><button className="rounded-xl bg-[#6e52b8] px-4 py-2.5 text-[12px] font-semibold text-white" onClick={() => { setShowAdd(false); toast.success("Teacher assignment saved."); }}>Save assignment</button></div></div></div>}
    </div>
  );
}

function Stat({ icon: Icon, value, label, tone }: { icon: typeof Users; value: string; label: string; tone: string }) { const classes: Record<string, string> = { lavender: "bg-[#eee9fb] text-[#7157ae]", mint: "bg-[#e9f5ef] text-[#579374]", peach: "bg-[#fff0e7] text-[#b47758]" }; return <div className="rounded-[18px] border border-[#ebe7f1] bg-white p-4 shadow-[0_5px_20px_rgba(60,45,92,.025)]"><div className="flex items-center justify-between"><span className="text-[11px] text-[#958c9e]">{label}</span><span className={`grid h-8 w-8 place-items-center rounded-xl ${classes[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-[25px] font-semibold tracking-[-.055em] text-[#40384d]">{value}</p></div>; }
function Field({ label, placeholder }: { label: string; placeholder: string }) { return <label className="text-[11px] font-semibold text-[#665d70]">{label}<input placeholder={placeholder} className="mt-2 w-full rounded-xl border border-[#e7e2ed] px-3 py-2.5 text-[12px] font-normal outline-none focus:border-[#a18ad1] focus:ring-4 focus:ring-[#f0ebfa]" /></label>; }
